---
title: "Ancestry Estimation"
output:
  rmdformats::robobook:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: false
    highlight: tango
params:
  populations: ../tests/data/populations.txt
  reference_pc_coord: ../tests/data/references.coord
  reference_samples: ../tests/data/references.samples
---

```{r setup, echo=FALSE, include=FALSE}

library(ggplot2)
library(dplyr)
library(DT)
```

## Summary

```{r echo=FALSE}
study_pc <- read.csv(params$populations, sep = '\t')
reference_pc <- read.csv(params$reference_pc_coord, sep = '\t')
reference_samples <- read.csv(params$reference_samples, sep = '\t')
reference_pc <- merge(reference_pc, reference_samples, by="indivID")

colors = c(
  "African" = "#FF6600",
  "Additional Asian Ancestries" ="#999999",		
  "European" = "#0099E6",
  "Greater Middle Eastern" = "#DBEE06",
  "Asian" = "#F90026",
  "East Asian" = "#FF99E6",
  "Additional Diverse Ancestries" = "#339933",
  "Hispanic or Latin American" = "#800080",
  "Unknown" = "#B5B5B5"
)

study_pc$population <- recode(study_pc$population,
  AFR = "African",
  ASN ="Additional Asian Ancestries",		
  EUR = "European",
  GME = "Greater Middle Eastern",
  SAS = "Asian",
  EAS = "East Asian",
  OTH = "Additional Diverse Ancestries",
  AMR = "Hispanic or Latin American",
  Unknown = "Unknown"
)

reference_pc$superpopID <- recode(reference_pc$superpopID,
  AFR = "African",
  ASN ="Additional Asian Ancestries",		
  EUR = "European",
  GME = "Greater Middle Eastern",
  SAS = "Asian",
  EAS = "East Asian",
  OTH = "Additional Diverse Ancestries",
  AMR = "Hispanic or Latin American",
  Unknown = "Unknown"
)

colorBlindBlack8  <- c("#E69F00", "#56B4E9", "#009E73", 
                       "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                       "#661100", "#6699CC", "#888888",
                       "#999999", "#E69F00", "#56B4E9", "#009E73", 
                       "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                       "#661100", "#6699CC", "#888888", "#999999")

study_summary <- study_pc %>%
  group_by(population) %>%
  count() %>%
 arrange(desc(n))

datatable(study_summary)

```

## PCA Plots

```{r echo=FALSE}

ggplot() +
  geom_point(data=reference_pc, aes(x=PC1, y=PC2, color = superpopID)) +
  geom_point(data=study_pc, aes(x=PC1, y=PC2, fill=population), colour="black", shape=24) +
  scale_color_manual(values =colors) +
  scale_fill_manual(values =colors) +
  labs(color = "") +
  guides(fill="none")+ 
  ggtitle(paste0(nrow(study_pc)," samples")) +  
  theme_bw()

ggplot() +
  geom_point(data=reference_pc, aes(x=PC3, y=PC4, color = superpopID)) +
  geom_point(data=study_pc, aes(x=PC3, y=PC4, fill=population), colour="black", shape=24) +
  scale_color_manual(values =colors) +
  scale_fill_manual(values =colors) +
  labs(color = "") +
  guides(fill="none")+ 
  ggtitle(paste0(nrow(study_pc)," samples")) +  
  theme_bw()

```

## Details

```{r echo=FALSE,  results='asis'}

for(i in 1:nrow(study_summary)) {
    row <- study_summary[i,]
    if (row$population == 'Unknown'){
      next
    }

    plot_details <- ggplot() +
    geom_point(data=reference_pc %>% filter(superpopID==row$population), aes(x=PC1, y=PC2, color = popID)) +
    geom_point(data=study_pc %>% filter(population==row$population), aes(x=PC1, y=PC2), colour="black", fill="black", shape=24) +
    scale_color_manual(values =colorBlindBlack8) +
    labs(color = "") +
    ggtitle(paste0(row$population," (", row$n ," samples)")) +
    theme_bw()
    
    print(plot_details)
    cat("\n")
}

```



## Samples

```{r echo=FALSE}
datatable(study_pc)
```